version: '3'

services:
  casinonode0:
    container_name: casinonode0
    image: "cosmicbet/casino-env"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-casino.log}
    volumes:
      # - ./build/node0:/root
      - ./build:/casino:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  casinonode1:
    container_name: casinonode1
    image: "cosmicbet/casino-env"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-casino.log}
    volumes:
      # - ./build/node1:/root
      - ./build:/casino:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  casinonode2:
    container_name: casinonode2
    image: "cosmicbet/casino-env"
    environment:
      - ID=2
      - LOG=${LOG:-casino.log}
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      # - ./build/node2:/root
      - ./build:/casino:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  casinonode3:
    container_name: casinonode3
    image: "cosmicbet/casino-env"
    environment:
      - ID=3
      - LOG=${LOG:-casino.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      # - ./build/node3:/root
      - ./build:/casino:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
